-- MySQL Script generated by MySQL Workbench
-- 04/27/16 14:17:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema geoprospect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geoprospect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geoprospect` DEFAULT CHARACTER SET utf8 ;
USE `geoprospect` ;

-- -----------------------------------------------------
-- Table `geoprospect`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoprospect`.`places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `place_id` VARCHAR(45) NULL,
  `nome` VARCHAR(128) NULL,
  `endereco` VARCHAR(256) NULL,
  `lat` VARCHAR(45) NULL,
  `lng` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `website` VARCHAR(85) NULL,
  `rua` VARCHAR(256) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(128) NULL,
  `estado` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `pais` INT NULL,
  `date_add` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geoprospect`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoprospect`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `empresa` VARCHAR(128) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geoprospect`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoprospect`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `palavra` VARCHAR(45) NULL,
  `total` INT NULL,
  `date_add` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consultas_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_consultas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `geoprospect`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geoprospect`.`emails_capturados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoprospect`.`emails_capturados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geoprospect`.`places_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoprospect`.`places_has_usuarios` (
  `places_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`places_id`, `usuarios_id`),
  INDEX `fk_places_has_usuarios_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_places_has_usuarios_places_idx` (`places_id` ASC),
  CONSTRAINT `fk_places_has_usuarios_places`
    FOREIGN KEY (`places_id`)
    REFERENCES `geoprospect`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_places_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `geoprospect`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
